_gui:
    resource: "@GuiBundle/Controller/"
    type:     annotation
    prefix:   /_gui

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

_gui_default:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /_gui
        permanent: true